### ISSUE TITLE
Release build fails to locate goog/events/events.js module

### ISSUE THREAD

**Issue by countgizmo** [thheller/shadow-cljs#908] opened 2021-06-28 12:29 UTC
Hi!

Firstly, thanks a lot for all your hard work. Shadow CLJS is really awesome!

I'm facing a problem and after a couple of days of debugging I'm totally stuck :(

I have recently updated my project to the latest Shadow CLJS version (2.11.6->2.14.5). Everything worked as before until I've tried to release build:
`internal module error, no mod for dep:[:shadow.build.classpath/resource "goog/events/events.js"]`

I couldn't figure out the root cause, but it happens only during the optimisation process and so far the `events.js` is the only file that causes the exception.

I've tracked down the problem to `org.clojure:google-closure-library:0.0-20201211-3e6c510d` being the source of that dependency, but when I download the JAR file I can see that `goog/events/events.js` is actually in there.

I have also discovered that the issue starts to happen on `2.12.0` (may it be related to the update of Closure compiler dependencies?).

My target is `npm-module` and the project uses `deps.edn`. 

I am already following the instructions in here https://shadow-cljs.github.io/docs/UsersGuide.html#failed-to-load just to be safe.

Please let me know if I can carry out additional debugging steps or if there's additional information I can provide.

**Comment by thheller** [comment] 2021-06-28 18:56
Hmm that error is specific to `:npm-module` builds. It tries to move every resource (source file) into a google closure module. I'm unsure why it fails for this one in particular. It has been around for ages and is not new.

Can you try just adding a `:require` in one (or more) of your namespaces for `goog.events`? So just `(:require [goog.events])` somewhere? Maybe that causes the placement code to get out of its quirk?

**Comment by countgizmo** [comment] 2021-06-29 10:03
Thanks for the reply!

I have tried adding `goog.events` as you've suggested. It didn't help.
So I went a different route. Since the project I've mentioned is proprietary and also has a bunch of other dependencies (re-frame, etc.) I've created a minimal project to reproduce the issue.

It's here: https://github.com/countgizmo/midnight-node-module

The interesting parts are:
1. When I remove `goog.events` from it, the `npm-module` actually builds in release without the mentioned error.
2. When I add it back, the issue returns. (so my guess is some transient dependency in my big project requires `goog.events`).
3. I have also tried `node-library` target. And this one doesn't have the problem (even with `goog.events` usage). I guess that's what you've mentioned in your comment saying that it only happens in `npm-module`.

I have provided steps to do both builds in the repo, hope it helps.

**Comment by thheller** [comment] 2021-06-29 17:29
Thanks for the repro. I can reproduce it so that helps a lot.

Not sure what is happening though. `:npm-module` has always been a bit of a hack so this isn't totally unexpected. I don't have a guess why it isn't working yet though. Everything looks fine.

**Comment by thheller** [comment] 2021-07-01 17:31
So I think I identified the problem being a circular dependency in the Closure Library code. I can re-order the code a bit but then the Closure Compiler still complains with a different error.

> Bad dependency: goog.events.eventtarget.js -> goog.events.events.js. Modules must be listed in dependency order.

I think this cannot be fixed in the current way `:npm-module` is structured since `JSModule` dependencies cannot be circular but the Closure Library sources can be. So creating one `JSModule` per source no longer works. The sources didn't use the be circular but now are. `:npm-module` kinda abused `JSModule` as they were never designed to be used that way. They are after all meant to group multiple sources, not have one source each.

I'll try to come up with a solution but I'd advise not using `:npm-module` in the first place since only that target will have that problem.

**Comment by countgizmo** [comment] 2021-07-02 15:18
Thank you for the details from your investigation!

I've noticed you've mentioned that `npm-module` is a hack in several places already (while googling for some hints for this issue). Are you thinking of deprecating this build target?

I guess the two alternatives are: `node-library` and `esm`. Although as I understand `esm` is still "beta".

**Comment by thheller** [comment] 2021-07-05 05:04
For now `:node-library` if you intend to publish to npm or integrate with any other node stuff. ESM still needs some more tweaks before it'll work properly in node envs.

**Closed** 2021-08-19 10:34 UTC
