### ISSUE TITLE
Can't find $jscomp when using "class Foo extends React.Component" syntax in local js files

### ISSUE THREAD

**Issue by gtebbutt** [thheller/shadow-cljs#643] opened 2020-01-24 15:32 UTC
Minimal reproduction at https://github.com/gtebbutt/reagent-react-native - I kept the diff there as small as possible, but I can confirm the same thing is happening on the latest RN version in the real project. 

Including function components from local js files works perfectly, but including any class component causes a `Can't find variable: $jscomp` error. 

This is my first attempt at moving from `lein` to `shadow-cljs`, so it's possible I've missed a setting somewhere. Any guidance is greatly appreciated!

**Comment by gtebbutt** [comment] 2020-01-24 16:17
It looks as though adding `:compiler-options {:output-feature-set :es6}` fixes the issue - I'd thought that was implicit in the `:target :react-native` but it looks like I was mistaken. 

Is there any reason not to use `es6` output in this case?

**Comment by thheller** [comment] 2020-01-24 17:33
> Is there any reason not to use es6 output in this case?

I don't know. If it runs then it should be fine?

`$jscomp` has come up several times. Unfortunately I have not yet figured out how to fix it properly. Polyfill handling is weird. If you can bump the `:output-feature-set` you definitely should keep it.

**Comment by gtebbutt** [comment] 2020-01-24 18:56
Yup, seems to be working well - thought it might have been off for a specific reason, but all looks good so far. Might even be a sensible default for `:react-native`, since it's going straight into Metro/Babel anyway and most code is ES6 in the React Native world.

**Comment by thheller** [comment] 2020-01-24 19:05
In development react-native/metro does not see the source so it doesn't process it in any way. It will however see the code in `release` builds so things might behave differently if it decides to rewrite code after all.

I don't do react-native development myself so I'm not sure about the current state of JS support. I'll happily make ES6 the default if that is confirmed safe. Although it only really matters when including JS directly which I'd expect to be rather uncommon.

**Comment by gtebbutt** [comment] 2020-01-24 21:41
The direct JS includes are definitely an edge case, but I was also thinking that it could increase overall efficiency in normal use by avoiding stacking Closure polyfills on top of Babel polyfills in the production code. I'm pretty much speculating on that one, though, I haven't actually dived into testing it.

**Comment by thheller** [comment] 2020-01-24 22:50
Since CLJS doesn't emit anything that requires polyfills they really only would be added by using custom JS or ES6 features via CLJS code, which in turn is totally controlled by `:output-feature-set`. So if you set it to `:es6` and only write ES6 code then no polyfills will be added unless metro wants to add some.

**Comment by thheller** [comment] 2020-05-10 07:42
`$jscomp` related issues should be fixed.

**Closed** 2020-05-10 07:41 UTC
