### ISSUE TITLE
Is there anything preventing autoload with warnings?

### ISSUE THREAD

**Issue by iku000888** [thheller/shadow-cljs#87] opened 2017-08-17 06:32 UTC
Thanks for a really useful tool.

Would be nice to get reloads when you have warnings that cannot be dealt with.

I noticed this line in the source:
https://github.com/thheller/shadow-cljs/blob/54875e76de7f88ac9a04f48bf03ecf04d30f9ce8/src/main/shadow/cljs/devtools/client/browser.cljs#L116

Is there anything outstanding that needs work before this is possible?

**Comment by arichiardi** [comment] 2017-08-17 07:52
Alternatively, there should be a way to disable [some warning](https://clojurescript.org/reference/compiler-options#warnings) at the ClojureScript compiler level

**Comment by thheller** [comment] 2017-08-17 08:09
I kinda like persistent warnings because it urges you to fix them.

I assume by "cannot be dealt with" you are talking about warnings from libraries? I thought about relaxing the reload requirements so that it reloads code from libraries regardless of warnings.

Otherwise I could add a toggle (like figwheel) that just disables the check and reloads everything.

Otherwise I don't think disabling warnings is a good idea, they are there for a reason and should be fixed.

**Comment by iku000888** [comment] 2017-08-17 08:14
@arichiardi thanks! It is a good point.

OTOH there seems to be warnings like this one that happens regardless of disabling the warning.
(Happens when including a third party lib/guessing it is a Clojure level thing during macro expantion?)


```
 macroexpand already refers to: cljs.core/macroexpand being replaced by: clojure.reflect/macroexpand
```

@thheller I agree warnings should be fixed, and a toggle would be really convenient. Just my 2 cents :)

**Comment by thheller** [comment] 2017-08-17 08:20
Weird warning, which file does this come from? `macroexpand` is a REPL/self-host thing and shouldn't ever be included in actual code?

**Comment by thheller** [comment] 2017-08-17 08:23
But to get rid of that warning you add `(:refer-clojure :exclude (macroexpand))` to the `ns` that refers it.

**Comment by iku000888** [comment] 2017-08-17 08:30
@thheller thanks for the pointer!
I do have a library that is a suspect but it has a lot of name spaces in it so have not tracked it down quite yet.

**Comment by thheller** [comment] 2017-08-17 08:32
The warning is reported with a file reference? All CLJS warnings should always have a file reference. If the warning is just printed to `*out*` when you run the compile it probably is inside a `.clj` macro file.

**Comment by iku000888** [comment] 2017-08-17 08:44
I get this warning, but seems to be gone when I do not include the library in the project.
Would love to get a minimal repro, but yeah life...

Suspected library is [clara-rules](https://github.com/cerner/clara-rules/) but I have nothing conclusive.

```
------ WARNING #1 --------------------------------------------------------------
 File: clojure/reflect.cljs
--------------------------------------------------------------------------------
  29 |   [sym cb]
  30 |   (query-reflection (str "var=" (js/encodeURIComponent (str sym)))
  31 |                     #(cb (evaluate-javascript %))))
  32 | 
  33 | (defn macroexpand
-------^------------------------------------------------------------------------
 macroexpand already refers to: cljs.core/macroexpand being replaced by: clojure.reflect/macroexpand
--------------------------------------------------------------------------------
  34 |   "Queries the reflection api with a quoted macro form, then calls the
  35 |   callback function with the macroexpanded form, as a string."
  36 |   [form]
  37 |   (query-reflection (str "macroform=" (js/encodeURIComponent (str form))) println))
  38 | 
--------------------------------------------------------------------------------
```

**Comment by iku000888** [comment] 2017-08-17 08:46
BTW really impressed with the pretty output format :)

**Comment by thheller** [comment] 2017-08-17 08:56
`clara-rules` is a bit scary. They do a whole bunch of macro trickery, I'm not sure if that is actually safe to do with the aggressive caching `shadow-cljs` does. Might need to disable caching at some point if you run into weird issues.

Besides that:
https://github.com/clojure/clojurescript/blob/master/src/main/cljs/clojure/reflect.cljs#L2

You can "fix" the warning by copying the file above into your source path and just adding the `:refer-clojure :exclude`. It will override the file from the `.jar`.

**Comment by iku000888** [comment] 2017-08-17 09:00
@thheller Thanks! That is an interesting solution.

At least I can at least confirm it has nothing to do with anything specific to shadow-cljs because I was getting the warning with the plain ClojureScript build api and figwheel.

**Comment by thheller** [comment] 2017-10-04 19:13
Just pushed https://github.com/thheller/shadow-cljs/commit/fe33a76fbd7454f4ede149bb123b7a6cf8741a2c.

That takes care of the most common scenario were warnings come from files in `.jar` files.

Still need to add a flag to ignore all warnings.

**Comment by iku000888** [comment] 2017-10-04 21:28
Woo hoo! awesome.

**Comment by thheller** [comment] 2017-11-13 16:55
I think I'm not going to add a flag.

Warning in jars now do not hinder reloading and warnings in project code should be fixed anyways.

If someone really had a compelling reason to still have a flag please re-open.

**Closed by thheller** 2017-11-13 16:55 UTC

**Comment by iku000888** [comment] 2017-11-13 17:40
Understandable & thanks for the workaround!

**Comment by staab** [comment] 2019-01-18 00:36
Hey there, is there a way to suppress displaying warnings for dependencies only, or even for a particular namespace? I don't want to disable _all_ warnings, or [_particular_ warnings](https://clojurescript.org/reference/compiler-options#warnings), but warnings quickly become useless when I have to dig through a bunch to find the ones in my code.

Your above suggestion (to copy the file into your path and modify it) makes sense, but seems tantamount to forking, which I'd rather not do to every dependency. It would be nice to just set up a namespace blacklist for the warning printer.

**Comment by thheller** [comment] 2019-04-09 16:47
Warnings in library code (ie. files in `.jar`) should not prevent reloads?

**Comment by Wonko7** [comment] 2019-04-10 17:15
Yes but warnings from other cljs stuff might. I'm having one with specter right now.
Let me know if I'm doing something wrong: I'm using it with `:dependencies [[com.rpl/specter "1.1.3-SNAPSHOT"]]`.
Everywhere I use a (setval ...) I get a `pathcacheXXX at line XXX is being replaced` warning. So yes, I will file an issue, and maybe one day I'll have time to track down the problem myself. 

In the meantime, I've resorted to disabling `:redef-in-file` altogether. The issue with this is that I would rather see the warnings so that if they happen in my code I can act on them, and if I only see them the library, they keep bugging me and reminding me that I'll have to take care of it.

**Comment by thheller** [comment] 2019-04-10 17:19
You can set `:devtools {:ignore-warnings true}` if I remember correctly. I think that isn't documented but should work?

**Comment by Wonko7** [comment] 2019-04-10 17:37
Yes! Exactly what I was looking for! Thanks!

**Comment by nikonikoniko** [comment] 2022-12-09 10:46
Hi all -  It seems like it does not work with `:rename` well, for example `(:refer-clojure :rename {identity clj-identity})` or is there something I am missing?

**Comment by thheller** [comment] 2022-12-10 09:05
It doesn't care which warning, should work for all. Maybe you have the config in the wrong place?

**Comment by nikonikoniko** [comment] 2022-12-10 10:08
Thanks for your response :)
 
 im not sure exactly what you mean. When I use `:refer-clojure :exclude` my project compiles, when I use `:refer-clojure :rename` it has a warning and does not recompile (in reagent the front end does not re load)

im happy to keep using `:exclude` for now, just thought you might want to know. Thanks!

**Comment by thheller** [comment] 2022-12-10 10:31
Well the obvious fix is to fix the warning. Nothing else really matters, it is there for a reason, so fix it.

Feel free to open a new issue if you have a reproducible full example, just `(:refer-clojure :rename {identity clj-identity})` in a `ns` form works fine for me.

**Comment by nikonikoniko** [comment] 2022-12-12 08:02
Interesting. Thanks, I’ll get a working example together.

thanks again for your time
