### ISSUE TITLE
Error compiling node "hello world": Assert failed: (satisfies? build-log/BuildLog logger)

### ISSUE THREAD

**Issue by chrisdavies** [thheller/shadow-cljs#130] opened 2017-11-10 15:03 UTC
The error message:

```
WARNING: failed to handle server msg {:type :start-autobuild}
java.lang.AssertionError: Assert failed: (satisfies? build-log/BuildLog logger)
```

package.json

```js
{
  "name": "shadowhi",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "shadow-cljs watch app",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "shadow-cljs": "^2.0.71"
  }
}
```

shadow-cljs.edn:

```edn
{:source-paths
 ["src"]

 :dependencies
 []

 :builds
 {:app
  {:target :node-script
   :output-dir "/dist"
   :modules {:main {:entries [shadowhi.core]}}}}}
```

src/shadowhi/core.cljs:

```cljs
(ns shadowhi.core
  (:require ["http" :as http]))

(js/console.log "HOI")

(def server (http/createServer (fn [req rsp]
                                  (.writeHead rsp 200 #js{"Content-Type" "text/plain"})
                                  (.end rsp "Hello, World!"))))

(.listen server 8080)

(js/console.log "Server running at http://0.0.0.0:8080")
```

**Comment by chrisdavies** [comment] 2017-11-10 16:03
Update:

```edn
{:source-paths
 ["src"]

 :dependencies
 []

 :builds
 {:app
  {:id :script
   :target :node-script
   :main shadowhi.core/main
   :output-to "dist/shadowhi.js"}}}
```

^^^ This got the compilation working, but still getting the same error when running `shadow-cljs watch` Does watch work with `:target :node-script`

**Comment by chrisdavies** [comment] 2017-11-10 16:37
Update, I got it working by cloning this project:

https://github.com/minimal-xyz/minimal-shadow-cljs-commonjs

I still get the error occasionally. It seems to happen when the `/target` directory gets corrupted in some way. I can `rm -rf target` and then run `npm run watch` and things work. But if I `ctrl+c` and then rerun `npm run watch` it almost always gives this error.

**Comment by thheller** [comment] 2017-11-10 16:44
I get this when trying to compile your example:

```
shadow-cljs watch app
shadow-cljs - config: /Users/zilence/code/tmp/shadowhi/shadow-cljs.edn version: 2.0.72
shadow-cljs - updating dependencies
shadow-cljs - dependencies updated
shadow-cljs - re-building aot cache on startup, that will take some time.
shadow-cljs - starting ...
shadow-cljs - watching build :app
[:app] Configuring build.
[:app] Compiling ...
[:app] Build failure:
The configured main "shadowhi.core/main" does not exist!
```

`:node-script` expects to find a function it will call when running the produced `dist/shadowhi.js`. I'd suggest creating a `(defn main [& args] ...)` and  putting the init call in there.

https://github.com/lambdaisland/npmdemo/tree/master/shadow-cljs

Also includes all the setup you'd need to code-reloading and the REPL.

Did you run `shadow-cljs` from the command line? Or from within `lein` or `boot`?

I'm not sure what to make of the error you posted.

**Comment by thheller** [comment] 2017-11-10 16:53
`target/shadow-cljs` should be completely isolated and only used by the tool itself. Do you have something else running that might be using the `target` directory? Nobody else reported any issues with this before.

You can try setting `:cache-root ".shadow-cljs"` in the `shadow-cljs.edn` (default is `"target/shadow-cljs"`) to make it not use the `target` directory.

**Comment by chrisdavies** [comment] 2017-11-10 17:01
Nothing else should be using it.

I'm on Mac High Sierra, Node v8.4.0.

It happens consistently any time I stop the watch and then restart it:

```
npm run watch
```

Then I wait for it to compile successfully, all's good.

```
ctrl + c
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! minimal-shadow-cljs-nodejs@0.1.0 watch: `shadow-cljs watch app`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the minimal-shadow-cljs-nodejs@0.1.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chris/.npm/_logs/2017-11-10T16_58_27_393Z-debug.log
```

Whatever. It errors when it's shutting down, but then when I re-run `npm run watch`


```
npm run watch

> minimal-shadow-cljs-nodejs@0.1.0 watch /Users/chris/dev/lang/clojure/minimal-shadow-cljs-nodejs
> shadow-cljs watch app

shadow-cljs - config: /Users/chris/dev/lang/clojure/minimal-shadow-cljs-nodejs/shadow-cljs.edn version: 2.0.72
shadow-cljs - starting ...
shadow-cljs - watching build :app
[:app] Configuring build.
Nov 10, 2017 11:58:45 AM clojure.tools.logging$eval454$fn__457 invoke
WARNING: failed to handle server msg {:type :start-autobuild}
java.lang.AssertionError: Assert failed: (satisfies? build-log/BuildLog logger)
	at shadow.build.api$with_logger.invokeStatic(api.clj:104)
	at shadow.build.api$with_logger.invoke(api.clj:104)
	at shadow.cljs.devtools.server.worker.impl$build_configure.invokeStatic(impl.clj:110)
	at shadow.cljs.devtools.server.worker.impl$build_configure.invoke(impl.clj:84)
	at shadow.cljs.devtools.server.worker.impl$eval3900$fn__3902.invoke(impl.clj:205)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at shadow.cljs.devtools.server.util$server_thread$fn__22819$fn__22820$fn__22824.invoke(util.clj:162)
	at shadow.cljs.devtools.server.util$server_thread$fn__22819$fn__22820.invoke(util.clj:161)
	at shadow.cljs.devtools.server.util$server_thread$fn__22819.invoke(util.clj:146)
	at clojure.core.async$thread_call$fn__7996.invoke(async.clj:442)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[:worker-error {:type :start-autobuild} #error {
 :cause "Assert failed: (satisfies? build-log/BuildLog logger)"
 :via
 [{:type java.lang.AssertionError
   :message "Assert failed: (satisfies? build-log/BuildLog logger)"
   :at [shadow.build.api$with_logger invokeStatic "api.clj" 104]}]
 :trace
 [[shadow.build.api$with_logger invokeStatic "api.clj" 104]
  [shadow.build.api$with_logger invoke "api.clj" 104]
  [shadow.cljs.devtools.server.worker.impl$build_configure invokeStatic "impl.clj" 110]
  [shadow.cljs.devtools.server.worker.impl$build_configure invoke "impl.clj" 84]
  [shadow.cljs.devtools.server.worker.impl$eval3900$fn__3902 invoke "impl.clj" 205]
  [clojure.lang.MultiFn invoke "MultiFn.java" 233]
  [shadow.cljs.devtools.server.util$server_thread$fn__22819$fn__22820$fn__22824 invoke "util.clj" 162]
  [shadow.cljs.devtools.server.util$server_thread$fn__22819$fn__22820 invoke "util.clj" 161]
  [shadow.cljs.devtools.server.util$server_thread$fn__22819 invoke "util.clj" 146]
  [clojure.core.async$thread_call$fn__7996 invoke "async.clj" 442]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1142]
  [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 617]
  [java.lang.Thread run "Thread.java" 745]]}]
```


... by the way, thanks for building shadow-cljs it's by far the easiest way to get up and running with Clojure for a non-Java guy. Great work!

**Comment by thheller** [comment] 2017-11-10 17:10
Can you paste `npx shadow-cljs info`? Are you using Java8?

I have no immediate explanation for the error.

```
npm run watch

> minimal-shadow-cljs-nodejs@0.1.0 watch /Users/zilence/code/tmp/minimal-shadow-cljs-nodejs
> shadow-cljs watch app

shadow-cljs - config: /Users/zilence/code/tmp/minimal-shadow-cljs-nodejs/shadow-cljs.edn version: 2.0.72
shadow-cljs - updating dependencies
shadow-cljs - dependencies updated
shadow-cljs - re-building aot cache on startup, that will take some time.
shadow-cljs - starting ...
shadow-cljs - watching build :app
[:app] Configuring build.
[:app] Compiling ...
[:app] Build completed. (38 files, 18 compiled, 0 warnings, 9.36s)

```

**Comment by chrisdavies** [comment] 2017-11-10 20:43
```
shadow-cljs - config: /Users/chris/dev/lang/clojure/minimal-shadow-cljs-nodejs/shadow-cljs.edn version: 2.0.72
=== Version
cli:            2.0.72
jar-version:    2.0.72
config-version: 2.0.72

=== Paths
cli:     /Users/chris/dev/lang/clojure/minimal-shadow-cljs-nodejs/node_modules/shadow-cljs/cli/dist/shadow.cljs.npm.cli.js
config:  /Users/chris/dev/lang/clojure/minimal-shadow-cljs-nodejs/shadow-cljs.edn
project: /Users/chris/dev/lang/clojure/minimal-shadow-cljs-nodejs
cache:   target/shadow-cljs

=== Java
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

=== Source Paths
/Users/chris/dev/lang/clojure/minimal-shadow-cljs-nodejs/src

=== Dependencies
cache-file: /Users/chris/dev/lang/clojure/minimal-shadow-cljs-nodejs/target/shadow-cljs/classpath.edn
[maven] com/cognitect/transit-clj/0.8.300/transit-clj-0.8.300.jar
[maven] com/fasterxml/jackson/core/jackson-core/2.8.7/jackson-core-2.8.7.jar
[maven] io/netty/netty-all/4.1.11.Final/netty-all-4.1.11.Final.jar
[maven] com/google/javascript/closure-compiler-unshaded/v20171023/closure-compiler-unshaded-v20171023.jar
[maven] org/msgpack/msgpack/0.6.12/msgpack-0.6.12.jar
[maven] org/clojure/tools.logging/0.4.0/tools.logging-0.4.0.jar
[maven] io/aleph/dirigiste/0.1.5/dirigiste-0.1.5.jar
[maven] commons-io/commons-io/2.5/commons-io-2.5.jar
[maven] net/java/dev/jna/jna/3.2.2/jna-3.2.2.jar
[maven] org/clojure/core.async/0.3.443/core.async-0.3.443.jar
[maven] org/clojure/google-closure-library/0.0-20170809-b9c14c6b/google-closure-library-0.0-20170809-b9c14c6b.jar
[maven] org/clojure/tools.nrepl/0.2.13/tools.nrepl-0.2.13.jar
[maven] manifold/manifold/0.1.6/manifold-0.1.6.jar
[maven] com/google/guava/guava/20.0/guava-20.0.jar
[maven] com/google/code/gson/gson/2.7/gson-2.7.jar
[maven] ring/ring-codec/1.0.1/ring-codec-1.0.1.jar
[maven] org/clojure/tools.cli/0.3.5/tools.cli-0.3.5.jar
[maven] com/google/errorprone/error_prone_annotations/2.0.18/error_prone_annotations-2.0.18.jar
[maven] thheller/shadow-cljsjs/0.0.3/shadow-cljsjs-0.0.3.jar
[maven] com/google/code/findbugs/jsr305/3.0.1/jsr305-3.0.1.jar
[maven] org/clojure/tools.analyzer/0.6.9/tools.analyzer-0.6.9.jar
[maven] org/clojure/clojurescript/1.9.946/clojurescript-1.9.946.jar
[maven] com/google/jsinterop/jsinterop-annotations/1.0.0/jsinterop-annotations-1.0.0.jar
[maven] org/clojure/java.classpath/0.2.3/java.classpath-0.2.3.jar
[maven] ring/ring-core/1.6.2/ring-core-1.6.2.jar
[maven] crypto-equality/crypto-equality/1.0.0/crypto-equality-1.0.0.jar
[maven] potemkin/potemkin/0.4.3/potemkin-0.4.3.jar
[maven] thheller/shadow-util/0.5.1/shadow-util-0.5.1.jar
[maven] org/clojure/core.memoize/0.5.9/core.memoize-0.5.9.jar
[maven] com/cognitect/transit-js/0.8.846/transit-js-0.8.846.jar
[maven] org/clojure/google-closure-library-third-party/0.0-20170809-b9c14c6b/google-closure-library-third-party-0.0-20170809-b9c14c6b.jar
[maven] com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar
[maven] hiccup/hiccup/1.0.5/hiccup-1.0.5.jar
[maven] clj-tuple/clj-tuple/0.2.2/clj-tuple-0.2.2.jar
[maven] aleph/aleph/0.4.4/aleph-0.4.4.jar
[maven] com/google/javascript/closure-compiler-externs/v20171023/closure-compiler-externs-v20171023.jar
[maven] primitive-math/primitive-math/0.1.5/primitive-math-0.1.5.jar
[maven] args4j/args4j/2.33/args4j-2.33.jar
[maven] riddley/riddley/0.1.14/riddley-0.1.14.jar
[maven] org/clojure/tools.reader/1.1.0/tools.reader-1.1.0.jar
[maven] org/clojure/core.specs.alpha/0.1.24/core.specs.alpha-0.1.24.jar
[maven] org/clojure/clojure/1.9.0-beta4/clojure-1.9.0-beta4.jar
[maven] thheller/shadow-cljs/2.0.72/shadow-cljs-2.0.72.jar
[maven] org/clojure/tools.analyzer.jvm/0.7.0/tools.analyzer.jvm-0.7.0.jar
[maven] com/google/protobuf/protobuf-java/3.0.2/protobuf-java-3.0.2.jar
[maven] expound/expound/0.3.1/expound-0.3.1.jar
[maven] org/ow2/asm/asm-all/4.2/asm-all-4.2.jar
[maven] org/clojure/data.json/0.2.6/data.json-0.2.6.jar
[maven] org/clojure/data.priority-map/0.0.7/data.priority-map-0.0.7.jar
[maven] com/cognitect/transit-cljs/0.8.243/transit-cljs-0.8.243.jar
[maven] commons-fileupload/commons-fileupload/1.3.2/commons-fileupload-1.3.2.jar
[maven] crypto-random/crypto-random/1.2.0/crypto-random-1.2.0.jar
[maven] hawk/hawk/0.2.11/hawk-0.2.11.jar
[maven] byte-streams/byte-streams/0.2.2/byte-streams-0.2.2.jar
[maven] org/mozilla/rhino/1.7R5/rhino-1.7R5.jar
[maven] thheller/shadow-client/1.1.0/shadow-client-1.1.0.jar
[maven] com/cognitect/transit-java/0.8.324/transit-java-0.8.324.jar
[maven] org/javassist/javassist/3.18.1-GA/javassist-3.18.1-GA.jar
[maven] net/incongru/watchservice/barbary-watchservice/1.0/barbary-watchservice-1.0.jar
[maven] org/clojure/core.cache/0.6.5/core.cache-0.6.5.jar
[maven] commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[maven] org/clojure/spec.alpha/0.1.143/spec.alpha-0.1.143.jar

```

**Comment by thheller** [comment] 2017-11-11 20:32
Looks good. Can you reproduce this when running with `npx shadow-cljs watch app` instead of `npm run watch`?

**Comment by thheller** [comment] 2018-01-19 12:29
Closing this since I was not able to reproduce. It may have been related to AOT.

**Closed by thheller** 2018-01-19 12:29 UTC
