### ISSUE TITLE
Not able to parse jose package for target :browser

### ISSUE THREAD

**Issue by karannakraTR** [thheller/shadow-cljs#1190] opened 2024-07-08 10:08 UTC
System Details : 
![image](https://github.com/thheller/shadow-cljs/assets/109527945/5a1cffa5-1c27-45b2-bc3f-393b5f6c3846)

Shadow-cljs version: 2.20.20
jose version: 5.2.4

Error Details:  I am trying to use jose package inside my shadow-cljs application but the development build is throwing this error

![image](https://github.com/thheller/shadow-cljs/assets/109527945/355e7514-167d-4066-8019-252cf24f1f31)

shadow-cljs.edn

![image](https://github.com/thheller/shadow-cljs/assets/109527945/47d319d0-c148-488d-86b8-c25e5238cd8c)

Additional information

![image](https://github.com/thheller/shadow-cljs/assets/109527945/29d3fa31-b817-43f0-b903-401e606b90a5)

That's how jose exports the modules for browser and I think export * as from "" is the root cause of the error

**Comment by thheller** [comment] 2024-07-08 13:03
I suspect the Closure Compiler just doesn't support the `export * as X` syntax. To be honest I didn't even know that existed. Seems like its maybe not that common? Not something I can do something about unfortunately. I tried searching the https://github.com/google/closure-compiler issues but couldn't find anything related.

`:js-provider :require` works because it means shadow-cljs is not processing any npm code. Of course also means something else must, which is not that easy for `:browser`.  You can try [:external](https://shadow-cljs.github.io/docs/UsersGuide.html#js-provider-external) and setup webpack or so.

**Comment by karannakraTR** [comment] 2024-07-08 13:10
I think this is such a common syntax, It can raise issues in future for sure. Also is there any doc which I can refer to but the easiest approach I think is to switch it with something else.

**Comment by thheller** [comment] 2024-07-08 13:26
Not much I can do. Its not `export * from ...` is common and supported, `export * as X from ...` I have never seen before, so not that common.

I reported it upstream to the Closure Compiler Team as it easily reproduces without shadow-cljs involved. Closing this as I can't do much on my end. Feel free to follow the linked issue.

**Closed by thheller** 2024-07-08 13:26 UTC

**Comment by kumarshantanu** [comment] 2025-12-02 13:03
Raised a corresponding point with Jose: https://github.com/panva/jose/discussions/832
