### ISSUE TITLE
Build status in dashboard becomes "unknown" after page reload

### ISSUE THREAD

**Issue by green-coder** [thheller/shadow-cljs#863] opened 2021-04-01 10:29 UTC
This is a *very minor* issue and I post it here in case I (or someone else) has the time to make a contribution in the next few weeks.

The status of a build is lost when we reload the page of the dashboard.

Before page reload:

![image](https://user-images.githubusercontent.com/598193/113281053-afece180-9317-11eb-930e-6ca1ae835dcc.png)

After page reload:

![image](https://user-images.githubusercontent.com/598193/113281161-c7c46580-9317-11eb-940e-8c1146f4de37.png)

**Comment by thheller** [comment] 2021-04-01 16:35
The problem is that the current build state is currently constructed by listening to the event stream which receives the `:build-start`, `:build-complete` messages etc. This is currently not stored anywhere server-side where the UI could access it on reload.

I've been meaning to fix this for a while now but as you say it is a very minor thing so I haven't gotten around to it yet.

**Comment by oxalorg** [comment] 2021-04-05 21:12
I'm trying to see if I can get the dashboard running locally, want to understand a bit more about the internals of shadow-cljs :) 

I spent some time trying to figure out what's going on, ran across a few issues (added shadow-experiments repo, figured out the need to watch :ui and and also appropriate npm installs everywhere)

Now I'm finally here, stuck at loading:

![image](https://user-images.githubusercontent.com/4194289/113627523-47886200-9681-11eb-9f51-43c15774bbd6.png)

Any ideas on how should I proceed and/or any other things to keep in mind while trying to work with this locally? Thanks!

**Comment by oxalorg** [comment] 2021-04-05 21:33
Okay I figured it out using postcss. After installing all the missing dependencies, this worked:
```
npx postcss src/css/ui.css -o .shadow-cljs/ui/css/ui.css
```
I am not sure if this is the correct way though!

**Comment by thheller** [comment] 2021-04-06 11:59
The UI build is currently in a bit of a messy state given how experimental everything arround it is. `master` has the fix for the above issue and I added the missing `package.json` as well. So you'd run `npm run ui-dev` to start the postcss process. The shadow-cljs build I start from the CLJS REPL.

**Comment by thheller** [comment] 2024-06-19 11:27
This was fixed in 2.28.9, sort of a side-effect of some other changes.

**Closed by thheller** 2024-06-19 11:27 UTC
