### ISSUE TITLE
Issues with Advanced compilation in 2.8.78 

### ISSUE THREAD

**Issue by BadAlgorithm** [thheller/shadow-cljs#611] opened 2019-12-04 01:03 UTC
Advanced compilation breaks with errors. e.g.:

"cannot read property 'prototype' of undefined" and "cannot read property '$cljs$core$IFn$_invoke$arity$1$' of undefined" for core dependencies e.g. cljs.spec, cljs.pprint and ajax.xml-http-request.

this occurred on version  2.8.74, 2.8.76 and 2.8.78.

Project successfully compiles in simple optimisations. However fails in advanced optimisations, even with --debug flag.

downgrading to 2.8.41 worked.

Is there way we can further debug and resolve these issues in the future?

**Comment by thheller** [comment] 2019-12-04 10:36
Hmm sorry about that. I added a new compiler tweak that could cause this if used incorrectly/accidentially (ie. the `^not-native` tag). That however would also break in development builds so I'm a bit confused. I also tested `cljs.spec` and `cljs.pprint` and those work fine. Will test the other one next.

You can try by submitting a stacktrace of where it fails when running with
```
shadow-cljs release app --pseudo-names
```
Looking at the generated JS might look strange but there should be a "namespace" somewhere with some clues.

**Comment by thheller** [comment] 2019-12-04 10:49
`cljs-ajax` also seems to work fine although I only tested with a basic request so it may fail elsewhere.

I may make the tweaks I made "more" opt-in. They kinda already are but maybe to use incorrectly. It would really help to have some reproducible example code.

**Comment by thheller** [comment] 2019-12-04 11:14
Please try `2.8.79`. I put the tweaks I added behind a compiler flag so it isn't enabled by default. That should take care of it. Would still very much like to find out why it was happening though.

**Comment by royalaid** [comment] 2019-12-05 03:40
Just want to say that I am also experiencing issues with advanced compilation. Specifically when moving from `2.8.67` to `2.8.68` when the app loads it throws `js.js:72 Uncaught ReferenceError: $jscomp is not defined` coming from `    at okta-sign-in.entry.js:14983` via the https://github.com/okta/okta-signin-widget package

**Comment by thheller** [comment] 2019-12-05 10:28
@royalaid the `$jscomp` issue should be fixed in newer releases. It is somehow caused by making `:output-wrapper true` the default even for multi-module builds. See https://github.com/thheller/shadow-cljs/issues/603.

**Comment by royalaid** [comment] 2019-12-05 17:30
Running against 2.8.80 leads to `Uncaught TypeError: $jscomp.initSymbol is not a function`

**Comment by thheller** [comment] 2019-12-05 19:24
Whenever an exception is thrown during load all other errors are most likely called by that missing code.

Do you have `:rewrite-polyfills` enabled? That seems to have gotten rather unreliable so I'd strongly recommend turning that off. Dunno why else it would try to polyfill Symbol.

**Comment by thheller** [comment] 2019-12-05 19:30
Also .. what the heck are you doing adding a package that is `1.7mb` in size? :P

**Comment by BadAlgorithm** [comment] 2019-12-06 12:21
@thheller Thank you for your response
 
Tried bumping to 2.8.79 and 2.8.80, still with the same results.

I've run shadow with --pseudo-names which give the following errors/stack trace.
```
Uncaught TypeError: Cannot read property 'prototype' of undefined
    at alpha.cljs:1309
    at core.cljs:177
```
```
pprint.cljs:2507 Uncaught TypeError: Cannot read property '$cljs$core$IFn$_invoke$arity$1$' of undefined
    at $cljs$pprint$check_flags$$ (pprint.cljs:2507)
    at $cljs$pprint$map_params$$ (pprint.cljs:2521)
    at Function.<anonymous> (pprint.cljs:2550)
    at $cljs$core$apply_to_simple$$ (core.cljs:3895)
    at $cljs$core$apply_to_simple$$ (core.cljs:3881)
    at Function.$APP.$cljs$core$apply$$.$cljs$core$IFn$_invoke$arity$2$ (core.cljs:3915)
    at $cljs$core$apply$$ (core.cljs:3915)
    at $cljs$pprint$consume$$ (pprint.cljs:89)
    at Function.$cljs$pprint$compile_format$$ (pprint.cljs:2684)
    at $cljs$core$apply_to_simple$$ (core.cljs:3895)
```
```
xml_http_request.cljs:67 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at xml_http_request.cljs:67
    at core.cljs:226
```

**Comment by filipesilva** [comment] 2020-01-24 20:42
I had a case with multi-modules there a lazy module failed to load unless I set `:output-wrapper false` when updating shadow-cljs from `2.8.67` to `2.8.68` (this release included a commit saying "make `:output-wrapper` for multi-module builds as well").

I traced the error by opening chrome devtools, selecting the `Sources` tab, then clicking on the `Pause on exceptions` button, and ticket the `Pause on caught exceptions` checkbox that appears.

I saw that shadow wrapper for a npm dependency would throw when using defineProperty on export. The debugger shows that the properties were already there.

![image](https://user-images.githubusercontent.com/4172079/73102508-e3e59f00-3ee9-11ea-99f9-c6bc5a3cac18.png).

The npm package in question is called `emoji-mart` and we import it like this on a lazy module:
```
  (:require
   [reagent.core :as r]
   ["emoji-mart/data/all.json" :as emoji-data]
   ["emoji-mart" :as emoji-mart])
```

For now we're keeping `:output-wrapper false`, it seems to work.

**Comment by benalbrecht** [comment] 2020-02-17 18:00
I'm seeing the same exception as @royalaid (different line numbers, depending on the exact distribution of modules) :
```
Cannot read property 'prototype' of undefined
    at alpha.cljs:1305
    at append.js:2
``` 
i only see the exception when turning on `Pause on caught exceptions` in chrome devtools. the exception occurs while loading/evaluating a module.

i'm using a multi-module build with `output-wrapper false`

haven't been able to create a minimal repro yet, but these are my current findings:

- happens on every version after 2.8.72 (e.g. it might be related to the upgrade to clojurescript `1.10.597`)
- it seems to manifest itself only when parts of `cljs.spec.alpha` are split between different modules

i'm suspecting this because when stepping through the code in the chrome debugger, i noticed that different functions of the exact *same* protocol implementations were calling `prototype` on *different* objects. some of these object did exist, others did not.

hope this helps in triaging the issue, i'll try to provide some more details in the next couple of days.

**Comment by filipesilva** [comment] 2020-02-17 19:23
@benalbrecht if you're seeing this error with clojure spec, I think you're running into https://clojure.atlassian.net/browse/CLJS-3207. The workaround is to also use `s/assert` on the main module.

**Comment by benalbrecht** [comment] 2020-02-17 22:51
thanks for the pointer @filipesilva!  `s/assert` fixed it 😄

**Comment by thheller** [comment] 2020-04-28 20:45
I ran into this issue in another project using `reitit` suffering the same `reify` related issue.

As of recent shadow-cljs versions it can be fixed by setting `:compiler-options {:cross-chunk-method-motion false}`. The trade-off is slightly worse code-splitting but it should be negligible.

**Closed by thheller** 2020-04-28 20:45 UTC
