### ISSUE TITLE
Be able to print circular data structures

### ISSUE THREAD

**Issue by peey** [thheller/shadow-cljs#822] opened 2021-01-02 14:10 UTC
Presently, inspecting a circular DS (where one of the js object properties point to the js object itself) in the REPL fails with

```
RangeError: Maximum call stack size exceeded
:shadow.cljs/print-error!
```

It seems that node repl truncates object nesting in its display to two levels, thus avoiding this issue

**Comment by thheller** [comment] 2021-01-02 14:34
`cljs.core` is the printing implementation used and thus can't be fixed via shadow-cljs.

You can use Inspect though. Just open the UI (default at http://localhost:9630) "Inspect Latest" and `(tap> (whatever-obj-or-expr))`  in your REPL.

**Closed by thheller** 2021-01-02 14:34 UTC

**Comment by peey** [comment] 2021-01-02 15:43
I'm using the node execution environment so not sure if the UI is still useful. 

Since the REPL is different from printing to stdout, I think I should still report this issue to one of the tools if not shadow-cljs.

Do you know where in the pipeline (emacs -> cider -> nREPL -> ???? -> shadow-cljs?) this change should be made?

**Comment by thheller** [comment] 2021-01-02 15:52
The problem you encounter is the "P" in "REPL". Printing is ultimately limited since not all objects can be represented as purely text without making "sacrifices". All implementations I'm aware of use `cljs.core` based printing which means the fix would need to be there in CLJS itself. Or you could create an alternate printing mechanism. My fix for this is Inspect.

**Comment by theophilusx** [comment] 2021-01-03 01:48
I'm not sure there is anything which really needs to be reported here.
Handling of circular data structures is a known challenge in all REPL
based languages. The problem is, any solution really needs to be
tailored to the specific requirement i.e. difficult to come up with a
solution which works for everyone. All solutions I've seen also impose
additional overhead, which is rarely needed as circular data structures
are not terribly common when working with functional data structures and
algorithms. The problem is a little like the halting problem - at what
point do you decide the DS is circular and give up printing? You might
say N, but my DS has N+1 nested elements and is not circular and I want
to print out my whole DS.

As Thomas points out, inspect is the common technique used when you need
to print a circular DS in the repl. This is also the recommended
solution when using just nodejs. Other approaches are to use the
cljs.pprint methods, which allow you to define a limit for circular
structures via a custom write function for the pprint dispatcher (I
woldn't be surprised if inspect doesn't use pprint 'under the hood').

You might also try the *print-length* and *print-level* settings for
core.print, which by default are nil and which can be used to limit the
number of items to be printed in a collection or the number of levels to
descend into an object when printing it. However, note that setting
these values affects all print calls and setting them too small could
have other unexpected results.
