### ISSUE TITLE
.shadow-cljs directory caching npm dependencies

### ISSUE THREAD

**Issue by chrisetheridge** [thheller/shadow-cljs#435] opened 2019-02-11 07:55 UTC
we've found a case in our shadow-cljs project where the `.shadow-cljs` folder was caching compiled node modules. 

we updated one of our modules (https://github.com/vahnag/react-timezone) to the latest version, and after shadow-cljs compiling, the compiled provided file in the browser was from the older version. we deleted node modules, cleaned target, updated shadow-cljs, to no avail. after trashing the `.shadow-cljs` dir, and  doing a fresh build, the newest version of the npm library was used.

strangely enough, when `cat`ing the `package.json` for react-timezone in my local `node_modules`, it was the correct (newer) version. so node modules was not incorrect or caching.

**Comment by thheller** [comment] 2019-02-11 09:50
There was a bug in the `npm` code that did not trigger a recompile in `watch` when `node_modules` files changed. Fixed in `shadow-cljs@2.7.32`.

This however is unrelated to actual caching and cannot exhibit the behavior you describe. I cannot reproduce this in any way.

This works as expected and invalidates `something` as it should. Contents of `package.json` are not relevant as only the actually installed files are used.
```
npm install something@version
npx shadow-cljs compile my-build
npm install something@other-version
npx shadow-cljs compile my-build
```

The same is now true for `watch` although it required restarting the `watch` before `2.7.32`. Is it possible shadow-cljs was running in server mode and the `watch` was never actually restarted inbetween anything else you tried?

**Comment by chrisetheridge** [comment] 2019-02-11 10:18
It is possible, but we start (and shut down) the shadow-cljs server from a build script. could that still leave a shadow server running, maybe if not exited cleanly?

**Comment by thheller** [comment] 2019-02-11 10:25
Hard to say. Not aware of any shutdown related bugs but there were some in the past so can't rule that out.

Next time just make sure to run `shadow-cljs compile your-build` at least once before wiping `.shadow-cljs`. It will tell you on startup if it using a running server instance or starting a new one.  A new process should definitely pick up any changes made to `node_modules`, if not we'd need to investigate further.

**Closed** 2019-02-12 05:08 UTC
