### ISSUE TITLE
Inconsistent behavior when using on two machines

### ISSUE THREAD

**Issue by mauricioszabo** [thheller/shadow-cljs#443] opened 2019-02-20 01:59 UTC
I'm using Shadow-CLJS with Devcards and Reagent to develop an Electron app: https://github.com/mauricioszabo/repl-tooling/tree/full-editor-tools.

I'm using two computers, both running Ubuntu Linux and both running on OpenJ9 VM. When I upgrade Shadow-CLJS on one computer, or upgrade npm libraries (or sometimes when I make a big change on one computer) shadow-cljs can't compile the code anymore.

The errors vary, but right now that's what's happened:

```
$ npx shadow-cljs watch integration
npx: installed 89 in 32.116s
shadow-cljs - config: /home/mauricio/.atom/packages/chlorine/repl-tooling/shadow-cljs.edn  cli version: 2.6.6  node: v10.6.0
shadow-cljs - updating dependencies
Retrieving check/check/0.0.3-SNAPSHOT/maven-metadata.xml from https://clojars.org/repo/
Retrieving thheller/shadow-cljs/2.6.6/shadow-cljs-2.6.6-aot.jar from https://clojars.org/repo/
shadow-cljs - dependencies updated
shadow-cljs - starting ...
fev 19, 2019 10:28:25 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.3.8.Final
fev 19, 2019 10:28:25 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.3.8.Final
shadow-cljs - server version: 2.6.6
shadow-cljs - server running at http://localhost:9630
shadow-cljs - socket REPL running on port 2233
shadow-cljs - nREPL server started on port 39286
shadow-cljs - watching build :integration
[:integration] Configuring build.
[:integration] Compiling ...
[:integration] Build failure:
------ ERROR -------------------------------------------------------------------
 File: jar:file:/home/mauricio/.m2/repository/org/clojure/clojurescript/1.10.339/clojurescript-1.10.339.jar!/cljs/pprint.cljs:2946:14
--------------------------------------------------------------------------------
2943 |         ((formatter-out "~w~:i") keyw)
2944 |         (loop [args args]
2945 |           (when (seq args)
2946 |             ((formatter-out " "))
--------------------^-----------------------------------------------------------
ClassCastException: clojure.lang.KeywordLookupSite$1 incompatible with clojure.lang.IFn
        clojure.spec.alpha/spec-impl/reify--1987 (alpha.clj:875)
        clojure.spec.alpha/conform (alpha.clj:150)
        clojure.spec.alpha/conform (alpha.clj:146)
        clojure.spec.alpha/macroexpand-check (alpha.clj:685)
        clojure.spec.alpha/macroexpand-check (alpha.clj:681)
        clojure.lang.Var.invoke (Var.java:385)
        cljs.analyzer/do-macroexpand-check (analyzer.cljc:3312)
        cljs.analyzer/do-macroexpand-check (analyzer.cljc:3306)
        cljs.analyzer/macroexpand-1* (analyzer.cljc:3326)
        cljs.analyzer/macroexpand-1* (analyzer.cljc:3314)
        cljs.analyzer/macroexpand-1 (analyzer.cljc:3375)
        cljs.analyzer/macroexpand-1 (analyzer.cljc:3371)
        cljs.analyzer/analyze-seq (analyzer.cljc:3408)
        cljs.analyzer/analyze-seq (analyzer.cljc:3388)
        ...
```

Then I tried again, deleting `.shadow-cljs` and `target` folders:

```
$ rm -R .shadow-cljs/ target/ -R
mauricio@lain ~/.atom/packages/chlorine/repl-tooling $ npx shadow-cljs watch integration
npx: installed 89 in 1.939s
shadow-cljs - config: /home/mauricio/.atom/packages/chlorine/repl-tooling/shadow-cljs.edn  cli version: 2.6.6  node: v10.6.0
shadow-cljs - updating dependencies
shadow-cljs - dependencies updated
shadow-cljs - starting ...
fev 19, 2019 10:29:49 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.3.8.Final
fev 19, 2019 10:29:49 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.3.8.Final
shadow-cljs - server version: 2.6.6
shadow-cljs - server running at http://localhost:9630
shadow-cljs - socket REPL running on port 2233
shadow-cljs - nREPL server started on port 41917
shadow-cljs - watching build :integration
[:integration] Configuring build.
[:integration] Compiling ...
[:integration] Build failure:
------ ERROR -------------------------------------------------------------------
 File: jar:file:/home/mauricio/.m2/repository/reagent/reagent/0.8.1/reagent-0.8.1.jar!/reagent/core.cljs:65:1
--------------------------------------------------------------------------------
  62 |   (assert-some c "Component")
  63 |   (comp/reactify-component c))
  64 | 
  65 | (defn render
-------^------------------------------------------------------------------------
ClassCastException: clojure.lang.KeywordLookupSite$1 incompatible with clojure.lang.IFn
        clojure.spec.alpha/spec-impl/reify--1987 (alpha.clj:875)
        clojure.spec.alpha/conform (alpha.clj:150)
        clojure.spec.alpha/conform (alpha.clj:146)
        clojure.spec.alpha/macroexpand-check (alpha.clj:685)
        clojure.spec.alpha/macroexpand-check (alpha.clj:681)
        clojure.lang.Var.invoke (Var.java:385)
        cljs.analyzer/do-macroexpand-check (analyzer.cljc:3312)
        cljs.analyzer/do-macroexpand-check (analyzer.cljc:3306)
        cljs.analyzer/macroexpand-1* (analyzer.cljc:3326)
        cljs.analyzer/macroexpand-1* (analyzer.cljc:3314)
        cljs.analyzer/macroexpand-1 (analyzer.cljc:3375)
        cljs.analyzer/macroexpand-1 (analyzer.cljc:3371)
        cljs.analyzer/analyze-seq (analyzer.cljc:3408)
        cljs.analyzer/analyze-seq (analyzer.cljc:3388)
        cljs.analyzer/analyze-form (analyzer.cljc:3578)
        cljs.analyzer/analyze-form (analyzer.cljc:3574)
        cljs.analyzer/analyze* (analyzer.cljc:3628)
        cljs.analyzer/analyze* (analyzer.cljc:3619)
        cljs.analyzer/analyze (analyzer.cljc:3649)
        cljs.analyzer/analyze (analyzer.cljc:3631)
        cljs.analyzer/analyze (analyzer.cljc:3640)
        cljs.analyzer/analyze (analyzer.cljc:3631)
        cljs.analyzer/analyze (analyzer.cljc:3638)
        cljs.analyzer/analyze (analyzer.cljc:3631)
        shadow.build.cljs-hacks/shadow-analyze-dot/fn--9739 (cljs_hacks.cljc:317)
        clojure.core/map/fn--5587 (core.clj:2745)
        clojure.lang.LazySeq.sval (LazySeq.java:40)
        ...
```

Then I ran `npm install`, removed folders again, and tried once more:

```
$ npm install
npm WARN REPL-Tooling-Integration@ No repository field.
npm WARN REPL-Tooling-Integration@ No license field.

$ npx shadow-cljs watch integration
shadow-cljs - config: /home/mauricio/.atom/packages/chlorine/repl-tooling/shadow-cljs.edn  cli version: 2.8.4  node: v10.6.0
shadow-cljs - updating dependencies
Retrieving nrepl/nrepl/0.6.0/nrepl-0.6.0.pom from https://clojars.org/repo/
Retrieving org/clojure/clojurescript/1.10.520/clojurescript-1.10.520.pom from https://repo1.maven.org/maven2/
Retrieving com/google/javascript/closure-compiler-unshaded/v20190121/closure-compiler-unshaded-v20190121.pom from https://repo1.maven.org/maven2/
Retrieving com/google/javascript/closure-compiler-main/v20190121/closure-compiler-main-v20190121.pom from https://repo1.maven.org/maven2/
Retrieving com/google/javascript/closure-compiler-parent/v20190121/closure-compiler-parent-v20190121.pom from https://repo1.maven.org/maven2/
Retrieving com/google/javascript/closure-compiler-externs/v20190121/closure-compiler-externs-v20190121.pom from https://repo1.maven.org/maven2/
Retrieving org/clojure/google-closure-library/0.0-20190213-2033d5d9/google-closure-library-0.0-20190213-2033d5d9.pom from https://repo1.maven.org/maven2/
Retrieving org/clojure/google-closure-library-third-party/0.0-20190213-2033d5d9/google-closure-library-third-party-0.0-20190213-2033d5d9.pom from https://repo1.maven.org/maven2/
Retrieving io/undertow/undertow-core/2.0.17.Final/undertow-core-2.0.17.Final.pom from https://repo1.maven.org/maven2/
..... lots of retrieving ...
^[0shadow-cljs - dependencies updated
shadow-cljs - server version: 2.8.4 running at http://localhost:9630
shadow-cljs - nREPL server started on port 44514
shadow-cljs - watching build :integration
[:integration] Configuring build.
[:integration] Compiling ...
[:failed-to-compare "^4.1.0" "4.1.1" #error {
 :cause "java.lang.Long incompatible with java.lang.String"
 :via
 [{:type java.lang.ClassCastException
   :message "java.lang.Long incompatible with java.lang.String"
   :at [clojure.core$subs invokeStatic "core.clj" 4981]}]
 :trace
 [[clojure.core$subs invokeStatic "core.clj" 4981]
  [clojure.core$subs invoke "core.clj" 4981]
  [shadow.cljs.devtools.server.npm_deps$get_major_java_version invokeStatic "npm_deps.clj" 19]
  [shadow.cljs.devtools.server.npm_deps$get_major_java_version invoke "npm_deps.clj" 11]
  [shadow.cljs.devtools.server.npm_deps$make_engine invokeStatic "npm_deps.clj" 25]
  [shadow.cljs.devtools.server.npm_deps$make_engine invoke "npm_deps.clj" 24]
  [shadow.cljs.devtools.server.npm_deps$fn__16952$fn__16953 invoke "npm_deps.clj" 43]
  [clojure.lang.Delay deref "Delay.java" 42]
  [clojure.core$deref invokeStatic "core.clj" 2320]
  [clojure.core$deref invoke "core.clj" 2306]
  [shadow.cljs.devtools.server.npm_deps$fn__16952$fn__16955 invoke "npm_deps.clj" 49]
 ... lots of errors like this one ...
[:integration] Build completed. (199 files, 198 compiled, 0 warnings, 25,69s)
```

Even with "build completed", code does not run:

```
Uncaught ReferenceError: $devcards is not defined
    at Object.devcards$system$render_cards [as render_cards] (devcards.system.js:315)
    at Object.devcards$system$main_cards_template [as main_cards_template] (devcards.system.js:322)
    at devcards.system.js:416
```

Even changing JVMs at this point didn't help..

**Comment by thheller** [comment] 2019-02-20 07:19
The last error was caused by a bug in `2.8.4` which is fixed in `2.8.5`. The other errors I can't really explain. Are the files shared between the computers or do both just use different `git` clones?

**Comment by mauricioszabo** [comment] 2019-02-20 17:44
Both just use different git clones. I'm not staging `.shadow-cljs` nor `target` folders.

What I can imagine is that incremental building is getting lost somehow when there are significant changes on the environment, be it multiple different files or different NPM packages...

Does it help if when things go wrong again, I post a gist with full stacktrace? What other elements can I add to help debugging this issue?

**Comment by thheller** [comment] 2019-02-20 17:48
So what are you doing exactly?

Machine A:
```
;; do some work
$ git commit
$ git push origin master
```

Machine B:
```
$ git pull origin master
$ npm install
$ shadow-cljs watch the-build
```

And it doesn't compile anymore?

**Comment by thheller** [comment] 2019-02-20 17:54
The error reported cannot be related to anything in shadow-cljs caches since you wiped them and the error still happened. I honestly have no clue what may be happening. Did you try OpenJDK with Hotstop instead of J9? I never used that one and have no idea what it does but maybe it just does weird things?

**Comment by mauricioszabo** [comment] 2019-02-20 18:00
Yes, that's exactly what I am doing. Sometimes removing these cached files work fine, otherwise I need to remove `node_modules` or something else.

As the error occurs on both machines, I'll try to use hotspot on one and J9 on other, and see if I can find more info on this issue!

**Comment by thheller** [comment] 2019-02-20 21:54
One thing you could try is setting `:aot false` in your `shadow-cljs.edn`. By default I ship AOT compiled classes since they improve `shadow-cljs` startup time quite substantially. Maybe there is some weird interaction with AOT compiled classes created on Hotspot vs J9? Seems kinda unlikely though.

**Comment by mauricioszabo** [comment] 2019-03-02 22:08
Same problem without `:aot false` and OpenJDK Hotspot:

```
$ java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```

Stacktrace (I also searched for my code to see if I was defining a `replace` function, or refering it, and did't find anything):

```
shadow-cljs - config: /home/mauricio/.atom/packages/chlorine/repl-tooling/shadow-cljs.edn  cli version: 2.8.8  node: v10.6.0
shadow-cljs - server version: 2.8.8 running at http://localhost:9630
shadow-cljs - nREPL server started on port 38201
shadow-cljs - watching build :integration
[:integration] Configuring build.
[:integration] Compiling ...
[:integration] Build completed. (199 files, 1 compiled, 0 warnings, 5,92s)
[:integration] Compiling ...
WARNING: replace already refers to: #'clojure.core/replace in namespace: clojure.string, being replaced by: #'clojure.string/replace
[:integration] Build failure:
compilation failed
{:tag :shadow.build.compiler/fail-many, :resource-ids ([:shadow.build.classpath/resource "repl_tooling/editor_integration/renderer.cljs"] [:shadow.build.classpath/resource "repl_tooling/integration/ui.cljs"]), :errors {[:shadow.build.classpath/resource "repl_tooling/editor_integration/renderer.cljs"] #error {
 :cause "Attempting to call unbound fn: #'clojure.string/replace"
 :via
 [{:type clojure.lang.ExceptionInfo
   :message "failed to compile resource: [:shadow.build.classpath/resource \"repl_tooling/editor_integration/renderer.cljs\"]"
   :data {:tag :shadow.build.compiler/compile-cljs, :resource-id [:shadow.build.classpath/resource "repl_tooling/editor_integration/renderer.cljs"], :source-id [:shadow.build.classpath/resource "repl_tooling/editor_integration/renderer.cljs"], :url #object[java.net.URL 0x1cc091e2 "file:/home/mauricio/.atom/packages/chlorine/repl-tooling/src/repl_tooling/editor_integration/renderer.cljs"], :file #object[java.io.File 0x213d05ca "/home/mauricio/.atom/packages/chlorine/repl-tooling/src/repl_tooling/editor_integration/renderer.cljs"], :ex-data nil}
   :at [shadow.build.compiler$maybe_compile_cljs$fn__11739 invoke "compiler.clj" 786]}
  {:type java.lang.IllegalStateException
   :message "Attempting to call unbound fn: #'clojure.string/replace"
   :at [clojure.lang.Var$Unbound throwArity "Var.java" 45]}]
 :trace
 [[clojure.lang.Var$Unbound throwArity "Var.java" 45]
  [clojure.lang.AFn invoke "AFn.java" 40]
  [cljs.compiler$emit_comment$print_comment_lines__3488 invoke "compiler.cljc" 771]
  [cljs.compiler$emit_comment invokeStatic "compiler.cljc" 781]
  [cljs.compiler$emit_comment invoke "compiler.cljc" 759]
  [cljs.compiler$fn__3519 invokeStatic "compiler.cljc" 807]
  [cljs.compiler$fn__3519 invoke "compiler.cljc" 801]
  [clojure.lang.MultiFn invoke "MultiFn.java" 229]
  [cljs.compiler$emit invokeStatic "compiler.cljc" 202]
  [cljs.compiler$emit invoke "compiler.cljc" 182]
  [shadow.build.cljs_hacks$emit1 invokeStatic "cljs_hacks.cljc" 582]
  [shadow.build.cljs_hacks$emit1 invoke "cljs_hacks.cljc" 575]
  [clojure.core$run_BANG_$fn__8775 invoke "core.clj" 7715]
  [clojure.lang.ArraySeq reduce "ArraySeq.java" 111]
  [clojure.core$reduce invokeStatic "core.clj" 6827]
  [clojure.core$run_BANG_ invokeStatic "core.clj" 7710]
  [clojure.core$run_BANG_ invoke "core.clj" 7710]
  [shadow.build.cljs_hacks$shadow_emitln invokeStatic "cljs_hacks.cljc" 594]
  [shadow.build.cljs_hacks$shadow_emitln doInvoke "cljs_hacks.cljc" 593]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [cljs.compiler$fn__3621 invokeStatic "compiler.cljc" 1044]
  [cljs.compiler$fn__3621 invoke "compiler.cljc" 1040]
  [clojure.lang.MultiFn invoke "MultiFn.java" 229]
  [cljs.compiler$emit invokeStatic "compiler.cljc" 202]
  [cljs.compiler$emit invoke "compiler.cljc" 182]
  [shadow.build.compiler$fn__11594 invokeStatic "compiler.clj" 264]
  [shadow.build.compiler$fn__11594 invoke "compiler.clj" 263]
  [clojure.lang.MultiFn invoke "MultiFn.java" 234]
  [shadow.build.compiler$do_compile_cljs_resource$fn__11649$fn__11652 invoke "compiler.clj" 491]
  [shadow.build.compiler$do_compile_cljs_resource$fn__11649 invoke "compiler.clj" 487]
  [shadow.build.compiler$do_compile_cljs_resource invokeStatic "compiler.clj" 450]
  [shadow.build.compiler$do_compile_cljs_resource invoke "compiler.clj" 408]
  [shadow.build.compiler$maybe_compile_cljs$fn__11739 invoke "compiler.clj" 744]
  [shadow.build.compiler$maybe_compile_cljs invokeStatic "compiler.clj" 743]
  [shadow.build.compiler$maybe_compile_cljs invoke "compiler.clj" 719]
  [shadow.build.compiler$par_compile_one invokeStatic "compiler.clj" 852]
  [shadow.build.compiler$par_compile_one invoke "compiler.clj" 807]
  [shadow.build.compiler$par_compile_cljs_sources$fn__11775$iter__11797__11801$fn__11802$fn__11803$fn__11804 invoke "compiler.clj" 925]
  [clojure.lang.AFn applyToHelper "AFn.java" 152]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 665]
  [clojure.core$with_bindings_STAR_ invokeStatic "core.clj" 1973]
  [clojure.core$with_bindings_STAR_ doInvoke "core.clj" 1973]
  [clojure.lang.RestFn invoke "RestFn.java" 425]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.core$apply invokeStatic "core.clj" 669]
  [clojure.core$bound_fn_STAR_$fn__5734 doInvoke "core.clj" 2003]
  [clojure.lang.RestFn invoke "RestFn.java" 397]
  [clojure.lang.AFn call "AFn.java" 18]
  [java.util.concurrent.FutureTask run "FutureTask.java" 266]
  [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1149]
  [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 624]
  [java.lang.Thread run "Thread.java" 748]]}, [:shadow.build.classpath/resource "repl_tooling/integration/ui.cljs"] #error {
 :cause "Attempting to call unbound fn: #'clojure.string/replace"
 :via
 [{:type clojure.lang.ExceptionInfo
   :message "failed to compile resource: [:shadow.build.classpath/resource \"repl_tooling/integration/ui.cljs\"]"
   :data {:tag :shadow.build.compiler/compile-cljs, :resource-id [:shadow.build.classpath/resource "repl_tooling/integration/ui.cljs"], :source-id [:shadow.build.classpath/resource "repl_tooling/integration/ui.cljs"], :url #object[java.net.URL 0x61140e66 "file:/home/mauricio/.atom/packages/chlorine/repl-tooling/test/repl_tooling/integration/ui.cljs"], :file #object[java.io.File 0x64495cf7 "/home/mauricio/.atom/packages/chlorine/repl-tooling/test/repl_tooling/integration/ui.cljs"], :ex-data nil}
   :at [shadow.build.compiler$maybe_compile_cljs$fn__11739 invoke "compiler.clj" 786]}
  {:type java.lang.IllegalStateException
   :message "Attempting to call unbound fn: #'clojure.string/replace"
   :at [clojure.lang.Var$Unbound throwArity "Var.java" 45]}]
 :trace
 [[clojure.lang.Var$Unbound throwArity "Var.java" 45]
  [clojure.lang.AFn invoke "AFn.java" 40]
  [cljs.compiler$emit_comment$print_comment_lines__3488 invoke "compiler.cljc" 771]
  [cljs.compiler$emit_comment invokeStatic "compiler.cljc" 781]
  [cljs.compiler$emit_comment invoke "compiler.cljc" 759]
  [cljs.compiler$fn__3519 invokeStatic "compiler.cljc" 807]
  [cljs.compiler$fn__3519 invoke "compiler.cljc" 801]
  [clojure.lang.MultiFn invoke "MultiFn.java" 229]
  [cljs.compiler$emit invokeStatic "compiler.cljc" 202]
  [cljs.compiler$emit invoke "compiler.cljc" 182]
  [shadow.build.cljs_hacks$emit1 invokeStatic "cljs_hacks.cljc" 582]
  [shadow.build.cljs_hacks$emit1 invoke "cljs_hacks.cljc" 575]
  [clojure.core$run_BANG_$fn__8775 invoke "core.clj" 7715]
  ...lots of lines...
```

I'll try to add `:aot false` too. It happened after I saved a file, the first build ran correctly.

**Comment by thheller** [comment] 2019-03-02 22:31
This is a completely different error than the ones you posted before?

Do you happen to use `tools.namespace` for something in this project? Like reloading code from the REPL?

**Comment by mauricioszabo** [comment] 2019-03-03 00:19
No, it's the same issue: I fire up with `npx shadow-cljs watch <build-id>`, and it doesn't compile or incremental compilation fails. Then I delete `.shadow-cljs` and things work fine again.

On this project, I have no `tools.namespace` on my classpath:

```
$ npx shadow-cljs clj-repl integration
shadow-cljs - config: /home/mauricio/projects/repl-tooling/shadow-cljs.edn  cli version: 2.8.8  node: v10.6.0
shadow-cljs - connected to server
shadow-cljs - REPL - see (help)
To quit, type: :repl/quit
[64:0]~shadow.user=> (clojure.core/require '[clojure.tools.namespace.repl])
Execution error (FileNotFoundException) at shadow.user/eval235451 (REPL:2).
Could not locate clojure/tools/namespace/repl__init.class, clojure/tools/namespace/repl.clj or clojure/tools/namespace/repl.cljc on classpath.
```

**Comment by thheller** [comment] 2019-03-03 07:17
> WARNING: replace already refers to: #'clojure.core/replace in namespace: clojure.string, being replaced by: #'clojure.string/replace

This is so weird.

Can you check your `(clojure.java.io/resource "clojure/string.clj")`? It is supposed to have
```
  (:refer-clojure :exclude (replace reverse))
```
I have no clue why you'd get such warnings? Are you maybe doing something weird in macros? Is this using something from bootstrap (eg. `cljs.js`)?

**Comment by mauricioszabo** [comment] 2019-03-13 16:35
I'm having this on `repl-tooling` project - I'm not using any macros on it, except some to ease tests, and nothing strange so far. Also, I'm not using bootstrap clojurescript, so nothing really strange here... it's literally the code that I referenced on the issue that I'm having trouble with...

**Comment by thheller** [comment] 2019-03-13 17:48
Since you are literally in a project called `repl-tooling` ... do you interact with the shadow-cljs server instance in ANY way via a REPL connection? Or does this happen completely standalone without your editor ever being connected to the server?

The log you posted had it compile fine once but then broke when trying to recompile. Did you maybe send something to the REPL? CLJ or CLJS? Anything at all? Maybe automated? You can't just send a wild `(require 'some.ns :reload-all)` over the wire for example.

**Comment by mauricioszabo** [comment] 2019-03-14 00:49
Wow, thanks! So, I _believe_ we're reaching the cause.

As far as I remember, I didn't send any command. But the problem is that it _can send_ this command to the CLJ REPL (not CLJS). So I'll do the following: if the error occurs again, I'll trace to see if a command was sent.

One question, is it possible that, if I send this `require` over the wire and crash my shadow-cljs compilation, that it somehow leaves something inconsistent so that, when I stop the watch process and start again, it can't compile anymore, even without sending anything?

**Comment by thheller** [comment] 2019-03-14 09:00
`shadow-cljs` keeps a bunch of state while running. If you `:reload-all` that state will be out of sync with the current runtime and blow up. Restarting the watch is not enough, you'll need to fully reset the running server which isn't possible remotely since that would kill your socket-repl connection.

A partial reload may be done via `(shadow.cljs.devtools.server/reload!)` but I make no guarantees that that will be reliable in any way (it will also stop all running processes, eg. `watch`). You really shouldn't use `:reload-all` in a running system ever.

**Comment by mauricioszabo** [comment] 2019-03-14 15:17
Ok, right! So, if I kill shadow-cljs and start again, it should work right? Because in more than one occasion even that didn't work, but I don't really remember if I sent any command to CLJ REPL (or if I was using Hotspot or OpenJ9 - probably OpenJ9).

Ok, so I'll try to check what are the conditions that gave me any of these errors, so I could see if it was an issue with OpenJ9, with connection to REPLs, and if these things are connected or not. Thanks again!

**Closed** 2019-08-08 20:58 UTC
Labels: cannot reproduce

**Comment by theronic** [comment] 2022-11-07 14:51
This happens to me if I do `shadow-cljs release` while there is an existing `shadow-cljs watch` instance running. If I stop the watch instance, I can do a release compile.

Ideally shadow-cljs should warn if it's going to be clobbered, or maybe it can use different target paths for release vs debug?

**Comment by thheller** [comment] 2022-11-07 15:26
You are free to configure where things go for release builds. See https://shadow-cljs.github.io/docs/UsersGuide.html#_release_specific_vs_development_configuration

```
:output-dir "bar"
:release {:output-dir "foo"}
```
